# Generated by Django 5.0.4 on 2024-05-06 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accountNumber",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("accountBalance", models.FloatField()),
                ("accountType", models.CharField(max_length=255)),
                ("accountName", models.CharField(max_length=255)),
                ("userId", models.CharField(max_length=255, unique=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("interest", models.FloatField()),
                ("duration", models.IntegerField()),
                ("loanStatus", models.CharField(max_length=255)),
                ("nextofkin", models.CharField(max_length=255)),
                ("approvedBy", models.CharField(max_length=255)),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("birthday", models.CharField(max_length=255)),
                ("phoneNumber", models.CharField(max_length=255, unique=True)),
                (
                    "profilepic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "accountId",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("isAdmin", models.BooleanField(default=False)),
                ("isActive", models.BooleanField(default=False)),
                ("membershipNumber", models.CharField(max_length=255)),
                ("membershipType", models.CharField(max_length=255)),
                (
                    "HomeAddress",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dateofbirth", models.DateTimeField()),
                ("nationality", models.CharField(max_length=255)),
                ("nationalId", models.CharField(max_length=255)),
                ("placeofwork", models.CharField(max_length=255)),
                ("natureofwork", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("MaritalStatus", models.CharField(max_length=255)),
                ("nextofkin", models.CharField(max_length=255)),
                ("nextofkinphone", models.CharField(max_length=255)),
                ("nextofkinaddress", models.CharField(max_length=255)),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user",
                        to="home.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transactionId", models.CharField(max_length=255, unique=True)),
                ("transactionType", models.CharField(max_length=255)),
                ("transactionAmount", models.FloatField()),
                ("transactionDate", models.DateTimeField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "transactionOwner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="home.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notificationId", models.CharField(max_length=255, unique=True)),
                ("notificationType", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "notificationOwner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="home.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("loanPaymentId", models.CharField(max_length=255, unique=True)),
                ("loanPaymentAmount", models.FloatField()),
                ("loanPaymentDate", models.DateTimeField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "loanPaymentOwner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_payments",
                        to="home.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("loanId", models.CharField(max_length=255, unique=True)),
                ("loanAmount", models.FloatField()),
                ("loanType", models.CharField(max_length=255)),
                ("loanStatus", models.CharField(max_length=255)),
                ("loanInterest", models.FloatField()),
                ("loanDuration", models.IntegerField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "loanOwner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="home.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="accountOwner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="home.user",
            ),
        ),
    ]
