# Generated by Django 5.0.4 on 2024-05-06 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_alter_account_userid_alter_user_membershipnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255, unique=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accountId', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('membershipNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('membershipType', models.CharField(max_length=255)),
                ('HomeAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateTimeField()),
                ('nationality', models.CharField(max_length=255)),
                ('nationalId', models.CharField(max_length=255)),
                ('placeofwork', models.CharField(max_length=255)),
                ('natureofwork', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('MaritalStatus', models.CharField(max_length=255)),
                ('nextofkin', models.CharField(max_length=255)),
                ('nextofkinphone', models.CharField(max_length=255)),
                ('nextofkinaddress', models.CharField(max_length=255)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='home.account')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='home_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='home_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='accountOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='home.customuser'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='home.customuser'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='loanPaymentOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payments', to='home.customuser'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notificationOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='home.customuser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.customuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
