# Generated by Django 5.0.4 on 2024-05-06 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='HomeAddress',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='MaritalStatus',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='account',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='accountId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='membershipNumber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='membershipType',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nationalId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='natureofwork',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nextofkin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nextofkinaddress',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nextofkinphone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='placeofwork',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profilepic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='a525cfa363', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255, unique=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accountId', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('membershipNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('membershipType', models.CharField(max_length=255)),
                ('HomeAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateTimeField()),
                ('nationality', models.CharField(max_length=255)),
                ('nationalId', models.CharField(max_length=255)),
                ('placeofwork', models.CharField(max_length=255)),
                ('natureofwork', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('MaritalStatus', models.CharField(max_length=255)),
                ('nextofkin', models.CharField(max_length=255)),
                ('nextofkinphone', models.CharField(max_length=255)),
                ('nextofkinaddress', models.CharField(max_length=255)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='home.account')),
            ],
        ),
    ]
