# Generated by Django 5.0.4 on 2024-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_users_birthday_notifications_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='earned',
            field=models.IntegerField(default=50000),
        ),
    ]
