# Generated by Django 5.0.4 on 2024-05-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_account_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='totalsavings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
