# Generated by Django 5.0.4 on 2024-05-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_account_totalsavings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userstatus',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
