# Generated by Django 5.0.4 on 2024-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_users_userstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
