# Generated by Django 5.0.4 on 2024-05-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transactionDescription",
            field=models.CharField(default="none", max_length=255),
        ),
    ]
