# Generated by Django 5.0.4 on 2024-06-05 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_transaction_transactionstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="PenaltyBalannce",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="Referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="approvedBy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="disbursement",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="duedate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="outstanding",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="totalPaid",
            field=models.FloatField(default=0),
        ),
    ]
